# Generated by Django 2.1 on 2018-09-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anne', models.DateField()),
                ('Commentaires', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Classe', models.CharField(max_length=100)),
                ('Niveau_Classe', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='')),
                ('Identifiant', models.TextField(max_length=100)),
                ('Nom', models.TextField(max_length=100)),
                ('Prenom', models.TextField(max_length=100)),
                ('Date_Naissance', models.DateField()),
                ('Lieu_Naissance', models.TextField(max_length=100)),
                ('Adresse', models.TextField(max_length=100)),
                ('Nationalite', models.TextField(max_length=100)),
                ('Date_Entree', models.TextField(max_length=100)),
                ('Niveau', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Inscription', models.DateField()),
                ('Type_Inscription', models.TextField(max_length=100)),
                ('Montant', models.FloatField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Maitre_Coranique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prenom', models.CharField(max_length=100)),
                ('Nom', models.TextField(max_length=100)),
                ('Adresse', models.TextField(max_length=100)),
                ('Telephone', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=100)),
                ('Type_Materiel', models.TextField(max_length=100)),
                ('Quantite', models.IntegerField()),
                ('Date_entree', models.DateTimeField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Matiere', models.CharField(max_length=255)),
                ('Type_Matiere', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Paiement', models.TextField(max_length=100)),
                ('Date_Paiement', models.DateTimeField()),
                ('Mois_Payer', models.DateField()),
                ('Montant', models.FloatField()),
                ('Mode_Reglement', models.TextField(max_length=40)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.TextField(max_length=100)),
                ('Numero_Telephone_1', models.TextField(max_length=18)),
                ('Numero_Telephone_2', models.TextField(max_length=18)),
                ('Numero_Telephone_3', models.TextField(max_length=18)),
                ('Adresse', models.TextField(max_length=200)),
                ('Ville', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Type_Parent', models.TextField(max_length=100)),
                ('Fonction', models.TextField(max_length=100)),
                ('Nationnalite', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Inscription'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='maitres',
            field=models.ManyToManyField(to='blog.Maitre_Coranique'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='materiels',
            field=models.ManyToManyField(to='blog.Materiel'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(to='blog.Parent'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='classe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Classe'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Eleve'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='matieres',
            field=models.ManyToManyField(to='blog.Matiere'),
        ),
    ]
