# Generated by Django 2.1 on 2018-09-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180913_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={},
        ),
    ]
