# Generated by Django 2.1 on 2018-09-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180913_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maitre_coranique',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={},
        ),
    ]
