# Generated by Django 2.1 on 2018-09-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180913_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
    ]
