# Generated by Django 2.1 on 2018-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180913_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='Date_entree',
            field=models.DateField(),
        ),
    ]
