# Generated by Django 2.1 on 2018-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180913_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='Date_Entree',
            field=models.DateField(),
        ),
    ]
